version: '3'
services:
  web:
    build: .
    environment:
      - PG_HOST=postgres
      - PG_USERNAME=postgres
    ports:
      - "443:443"
      - "80:80"
    links:
      - postgres
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  postgres:
    image: "postgres:10.1"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
