version: '3'
services:
  web:
    build: .
    environment:
      - PG_HOST=postgres
      - PG_USERNAME=postgres
    ports:
     - "443:443"
    links:
      - postgres
  postgres:
    image: "postgres:10.1"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
